// Project Euler (http://projecteuler.net/)
// Problem 2
//
// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.
//
// Answer: 4613732
// Execution time: 0m0.003s

#include <iostream>

using namespace std;

int main()
{
  int first = 1, second = 2, next;
  int sum = 2;

  while ((next = first + second) < 4000000)
  {
    if (next % 2 == 0)
      sum += next;

    first = second;
    second = next;
  }

  cout << sum << endl;
}
